# Generated by Django 4.2.18 on 2025-01-27 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0003_alter_matterfile_file"),
        ("payments", "0002_alter_payment_matter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="matter",
            field=models.ForeignKey(
                default=90,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="matters.matter",
            ),
            preserve_default=False,
        ),
    ]
