# Generated by Django 4.2.18 on 2025-02-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_delegated_admin",
            field=models.BooleanField(
                default=False,
                help_text="Markera om denna användare är en delegerad admin.",
                verbose_name="Delegated admin",
            ),
        ),
    ]
