# Generated by Django 4.2.18 on 2025-02-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_is_delegated_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gdpr_consent",
            field=models.BooleanField(
                default=False,
                help_text="Användaren har godkänt våra villkor och integritetspolicy.",
                verbose_name="GDPR-samtycke",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gdpr_consent_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="GDPR-samtyckesdatum"
            ),
        ),
    ]
