# Generated by Django 4.2.18 on 2025-02-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_gdpr_consent_customuser_gdpr_consent_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="two_factor_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
