# Generated by Django 4.2.18 on 2025-02-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_totp_secret_customuser_two_factor_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
