# Generated by Django 4.2.18 on 2025-02-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customuser_totp_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bank_account",
            field=models.CharField(
                blank=True,
                help_text="Ange ditt bankkonto (IBAN eller kontonummer) dit betalningar ska skickas.",
                max_length=50,
                null=True,
                verbose_name="Bankkonto",
            ),
        ),
    ]
