# Generated by Django 4.2.18 on 2025-03-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_bank_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="stripe_account_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Express-konto för delegerad admin",
                max_length=255,
                null=True,
            ),
        ),
    ]
