# Generated by Django 4.2.18 on 2025-02-13 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matters", "0003_alter_matterfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="matter",
            name="delegated_admins",
            field=models.ManyToManyField(
                blank=True,
                help_text="Delegated admin-användare som har administratörsrättigheter för detta ärende.",
                limit_choices_to={"is_delegated_admin": True},
                related_name="delegated_matters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
